# Generated by Django 5.1.2 on 2025-11-14 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('copy_json', models.JSONField(default=list, help_text='Array of paragraph strings')),
                ('gallery_json', models.JSONField(default=list, help_text='Array of {url, alt} objects')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='CONTACT', max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('intro_text', models.TextField()),
                ('background_image', models.URLField(blank=True, max_length=500)),
                ('socials_label', models.CharField(default='FOLLOW MADRID MARBLE', max_length=100)),
                ('form_submit_label', models.CharField(default='Submit inquiry', max_length=100)),
                ('form_disclaimer', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('href', models.URLField(blank=True, help_text='Optional link (mailto: or tel:)')),
                ('info_type', models.CharField(choices=[('address', 'Address'), ('email', 'Email'), ('phone', 'Phone')], default='address', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_href', models.CharField(default='#contact', max_length=200)),
                ('cta_icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Section',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='MM', max_length=10)),
                ('note', models.CharField(default='Madrid Marble. All rights reserved.', max_length=200)),
                ('links_json', models.JSONField(default=list, help_text='Array of {label, href} objects')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('headline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('primary_cta_label', models.CharField(blank=True, max_length=100)),
                ('primary_cta_href', models.CharField(default='#contact', max_length=200)),
                ('primary_cta_icon', models.CharField(blank=True, max_length=50)),
                ('secondary_cta_label', models.CharField(blank=True, max_length=100)),
                ('secondary_cta_href', models.CharField(blank=True, max_length=200)),
                ('testimonial_quote', models.TextField(blank=True)),
                ('testimonial_name', models.CharField(blank=True, max_length=100)),
                ('testimonial_meta', models.CharField(blank=True, max_length=100)),
                ('testimonial_stars', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('secure_url', models.URLField(max_length=500)),
                ('web_url', models.URLField(help_text='Optimized variant: f_auto,q_auto', max_length=500)),
                ('thumb_url', models.URLField(help_text='Thumbnail variant: c_fill,g_face,w_480,h_320', max_length=500)),
                ('bytes_size', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('tags_csv', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Asset',
                'verbose_name_plural': 'Media Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(default='MM', max_length=10)),
                ('brand', models.CharField(default='Madrid Marble', max_length=100)),
                ('links_json', models.JSONField(default=list, help_text='Array of {label, href} objects')),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_href', models.CharField(default='#contact', max_length=200)),
            ],
            options={
                'verbose_name': 'Navigation',
                'verbose_name_plural': 'Navigation',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('feature_image_url', models.URLField(blank=True, max_length=500)),
                ('feature_image_alt', models.CharField(blank=True, max_length=200)),
                ('feature_title', models.CharField(blank=True, max_length=200)),
                ('feature_description', models.TextField(blank=True)),
                ('feature_tags_json', models.JSONField(default=list, help_text='Array of tag strings')),
                ('feature_testimonial_quote', models.TextField(blank=True)),
                ('feature_testimonial_author', models.CharField(blank=True, max_length=200)),
                ('feature_cta_label', models.CharField(blank=True, max_length=100)),
                ('feature_cta_href', models.CharField(default='#contact', max_length=200)),
                ('feature_cta_icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Portfolio Section',
                'verbose_name_plural': 'Portfolio Section',
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('image_alt', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('canonical', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.TextField(blank=True, max_length=300)),
                ('og_image', models.URLField(blank=True)),
                ('favicon', models.URLField(blank=True)),
                ('preload_hero', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('is_open', models.BooleanField(default=False, help_text='Open by default in accordion')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Services Section',
                'verbose_name_plural': 'Services Section',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('href', models.URLField(max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('avatar', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('tel', 'Phone'), ('textarea', 'Textarea')], default='text', max_length=20)),
                ('placeholder', models.CharField(max_length=200)),
                ('span', models.IntegerField(default=1, help_text='Grid span: 1 or 2')),
                ('rows', models.IntegerField(default=5, help_text='For textarea only')),
                ('required', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='myApp.contact')),
            ],
            options={
                'verbose_name': 'Contact Form Field',
                'verbose_name_plural': 'Contact Form Fields',
                'ordering': ['sort_order'],
            },
        ),
    ]
