# Generated by Django 5.1.2 on 2025-11-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='logo_image_url',
            field=models.URLField(blank=True, help_text='Logo image URL (if provided, this will be used instead of logo_text)', max_length=500),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='logo_text',
            field=models.CharField(default='MM', help_text='Fallback text if logo image is not provided', max_length=10),
        ),
    ]
