# Generated by Django 5.1.2 on 2025-11-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_navigation_logo_image_url_alter_navigation_logo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If unchecked, this project will be hidden from the frontend'),
        ),
    ]
