# Generated by Django 5.0.1 on 2025-11-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_portfolioproject_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Featured Service',
                'verbose_name_plural': 'Featured Services',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Featured Services', max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Featured Services Section',
                'verbose_name_plural': 'Featured Services Section',
            },
        ),
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Promise', max_length=200)),
                ('main_statement', models.TextField(help_text='Main promise statement')),
                ('substatement', models.TextField(blank=True, help_text='Supporting statement')),
                ('closing_statement', models.TextField(blank=True, help_text='Closing statement (italic text)')),
            ],
            options={
                'verbose_name': 'Promise Section',
                'verbose_name_plural': 'Promise Section',
            },
        ),
        migrations.CreateModel(
            name='PromiseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Font Awesome icon class (e.g., 'fa-solid fa-gem')", max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Promise Card',
                'verbose_name_plural': 'Promise Cards',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WhyTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Clients Trust Madrid Marble', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Subtitle/description')),
            ],
            options={
                'verbose_name': 'Why Trust Section',
                'verbose_name_plural': 'Why Trust Section',
            },
        ),
        migrations.CreateModel(
            name='WhyTrustFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why Trust Factor',
                'verbose_name_plural': 'Why Trust Factors',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='hero',
            name='eyebrow',
            field=models.CharField(blank=True, help_text="Text above headline (e.g., 'Premium Marble Works for Homes, Hotels...')", max_length=200),
        ),
        migrations.AddField(
            model_name='hero',
            name='stats_json',
            field=models.JSONField(blank=True, default=list, help_text='Array of {value, label, description} objects for hero stats'),
        ),
    ]
