# Generated by Django 5.0.1 on 2025-11-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_aboutpage_contactpage_faqpage_portfoliopage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='href',
            field=models.URLField(blank=True, help_text='Optional link (mailto:, tel:, or https://wa.me/)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='info_type',
            field=models.CharField(choices=[('address', 'Address'), ('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='address', max_length=20),
        ),
    ]
