# Generated by Django 5.1.2 on 2025-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_contactinfo_href_alter_contactinfo_info_type'),
    ]

    operations = [
        # Remove before_after fields (no longer used)
        migrations.RemoveField(
            model_name='portfoliopage',
            name='before_after_description',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='before_after_title',
        ),
        
        # Add Hero Section fields
        migrations.AddField(
            model_name='portfoliopage',
            name='hero_badge',
            field=models.CharField(blank=True, help_text='Badge text above hero title', max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='hero_image_1_url',
            field=models.URLField(blank=True, help_text='First rotating hero image', max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='hero_image_1_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='hero_image_2_url',
            field=models.URLField(blank=True, help_text='Second rotating hero image', max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='hero_image_2_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='hero_image_3_url',
            field=models.URLField(blank=True, help_text='Third rotating hero image', max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='hero_image_3_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        
        # Add Residential Section fields
        migrations.AddField(
            model_name='portfoliopage',
            name='residential_badge',
            field=models.CharField(blank=True, help_text='Badge text for residential section', max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='residential_featured_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='residential_featured_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='residential_featured_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='residential_featured_description',
            field=models.TextField(blank=True),
        ),
        
        # Add Commercial Section fields
        migrations.AddField(
            model_name='portfoliopage',
            name='commercial_badge',
            field=models.CharField(blank=True, help_text='Badge text for commercial section', max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='commercial_featured_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='commercial_featured_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='commercial_featured_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='commercial_featured_description',
            field=models.TextField(blank=True),
        ),
        
        # Add CTA Section fields
        migrations.AddField(
            model_name='portfoliopage',
            name='cta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='cta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='cta_primary_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='cta_primary_href',
            field=models.CharField(default='/contact/', max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='cta_secondary_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopage',
            name='cta_secondary_href',
            field=models.CharField(default='/services/', max_length=200),
        ),
    ]

