# Generated by Django 5.1.2 on 2025-11-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_update_portfoliopage_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopagecategory',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the category'),
        ),
        migrations.AddField(
            model_name='portfoliopagecategory',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Image alt text', max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliopagecategory',
            name='image_url',
            field=models.URLField(blank=True, help_text='Category image URL', max_length=500),
        ),
    ]
